USE UTMEurope3;

ALTER TABLE UTMEurope3_Flights
  ADD COLUMN IF NOT EXISTS route_geom LINESTRING SRID 4326
      GENERATED ALWAYS AS (ST_GeomFromGeoJSON(UTME3FLT_Route_GeoJSON)) STORED,
  ADD SPATIAL INDEX IF NOT EXISTS idx_flt_route (route_geom),
  ADD INDEX IF NOT EXISTS idx_flt_time (UTME3FLT_Time_Start, UTME3FLT_Time_End);

ALTER TABLE UTMEurope3_Zones
  ADD COLUMN IF NOT EXISTS UTME3ZON_valid_from DATETIME NULL,
  ADD COLUMN IF NOT EXISTS UTME3ZON_valid_to   DATETIME NULL,
  ADD COLUMN IF NOT EXISTS UTME3ZON_floor_m    INT NULL,
  ADD COLUMN IF NOT EXISTS UTME3ZON_ceiling_m  INT NULL,
  ADD COLUMN IF NOT EXISTS zone_geom POLYGON SRID 4326
      GENERATED ALWAYS AS (ST_GeomFromGeoJSON(UTME3ZON_GeoJSON)) STORED,
  ADD SPATIAL INDEX IF NOT EXISTS idx_zone_geom (zone_geom),
  ADD INDEX IF NOT EXISTS idx_zone_valid (UTME3ZON_valid_from, UTME3ZON_valid_to);

ALTER TABLE UTMEurope3_Notams
  ADD COLUMN IF NOT EXISTS UTME3NTM_Severity ENUM('hard','soft') DEFAULT 'hard',
  ADD COLUMN IF NOT EXISTS notam_geom GEOMETRY SRID 4326
      GENERATED ALWAYS AS (ST_GeomFromGeoJSON(UTME3NTM_Zone)) STORED,
  ADD SPATIAL INDEX IF NOT EXISTS idx_notam_geom (notam_geom),
  ADD INDEX IF NOT EXISTS idx_notam_valid (UTME3NTM_Start, UTME3NTM_End);

ALTER TABLE UTMEurope3_Weather
  ADD COLUMN IF NOT EXISTS UTME3WTH_lat DECIMAL(9,6) NULL,
  ADD COLUMN IF NOT EXISTS UTME3WTH_lon DECIMAL(9,6) NULL,
  ADD COLUMN IF NOT EXISTS UTME3WTH_valid_to DATETIME NULL,
  ADD COLUMN IF NOT EXISTS weather_point POINT SRID 4326
      GENERATED ALWAYS AS (IF(UTME3WTH_lat IS NULL OR UTME3WTH_lon IS NULL,
                              NULL, ST_SRID(POINT(UTME3WTH_lon, UTME3WTH_lat), 4326))) STORED,
  ADD SPATIAL INDEX IF NOT EXISTS idx_weather_point (weather_point),
  ADD INDEX IF NOT EXISTS idx_weather_valid (UTME3WTH_observed_at, UTME3WTH_valid_to);

ALTER TABLE UTMEurope3_Emergencies
  ADD COLUMN IF NOT EXISTS em_point POINT SRID 4326
      GENERATED ALWAYS AS (IF(UTME3EMG_lat IS NULL OR UTME3EMG_lon IS NULL,
                              NULL, ST_SRID(POINT(UTME3EMG_lon, UTME3EMG_lat), 4326))) STORED,
  ADD SPATIAL INDEX IF NOT EXISTS idx_em_point (em_point);

ALTER TABLE UTMEurope3_Conflicts
  ADD COLUMN IF NOT EXISTS conflict_geom GEOMETRY SRID 4326 NULL,
  ADD SPATIAL INDEX IF NOT EXISTS idx_conflict_geom (conflict_geom);
